name: Deploy workflow

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  deploy-backend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger render deployment
        run: |
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"